### ISSUE TITLE
能提供百度云盘链接吗

### ISSUE THREAD

**Issue by xiaozhiliaoo** [songhuiqing/book#3]
这个下载下来太慢了，能提供百度云盘链接吗？

**Comment by cobb-tx** [comment]
什么东西的 百度云盘链接&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiaozhiliao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月4日(星期二) 凌晨0:38
收件人:&nbsp;"songhuiqing/book"<book@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[songhuiqing/book] 能提供百度云盘链接吗 (#3)




这个下载下来太慢了，能提供百度云盘链接吗？

**Comment by xiaozhiliaoo** [comment]
你电子书的云盘链接，下载你这些太慢了

**Comment by ANWSY** [comment]
同求，用git 下载太慢了

**Comment by ANWSY** [comment]
同求，用git 下载太慢了

**Comment by dahuoyzs** [comment]
https://github.com/dahuoyzs/javapdf
